### ISSUE TITLE
1.1 Functional Requirements

### ISSUE THREAD

**Issue by DIBASHGH1** [Group-S1-Tech-Domain/Mid-Project-Deliverables#8]

**Comment by Prem49B** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:////Users/prembhattarai/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

<link rel=themeData
href="file:////Users/prembhattarai/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:////Users/prembhattarai/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-AU style='tab-interval:36.0pt;word-wrap:break-word'>


<h2 style='line-height:200%'><span lang=EN-US style='font-size:12.0pt;
line-height:200%;font-family:"Times New Roman",serif;color:black;mso-themecolor:
text1'><o:p>&nbsp;</o:p></span></h2>

<h2 style='line-height:200%'><a name="_Toc135222750"><b><span lang=EN-US
style='font-size:12.0pt;line-height:200%;font-family:"Times New Roman",serif;
color:black;mso-themecolor:text1'>Functional Requirements:</span></b></a><b><span
lang=EN-US style='font-size:12.0pt;line-height:200%;font-family:"Times New Roman",serif;
color:black;mso-themecolor:text1'><o:p></o:p></span></b></h2>



FR No. | Functional Requirements | Components | Comments
-- | -- | -- | --
FR1 | User Registration | signup.php | User registration is a necessary functional   requirement for the system since it allows new users to register an account   and use the system's services. To avoid unwanted access or data breaches, the   system should securely store user registration data.
FR2 | Track the progress of test report | Appointments.php, Appointment_detail.php | This parameter allows users to follow the   status of their test reports. By delivering real-time updates on the status   of the report, it ensures transparency and improves user experience.
FR3 | Booking the test | Appointment.php,   Appointment_confirmation.php | The aim is for users to be able to arrange   appointments for lab testing. Users should be able to choose the sort of a   convenient time and place, and confirm the appointment.
FR4 | Price details of each services/test | Service-detail.php | This functional requirement will give the   user with pricing information for each service or test provided by the   system. This will assist the user in making a knowledgeable choice before   scheduling a test.
FR5 | Paying the fees/ choosing payment method | Payment.php | This functional requirement aims to give   the user the possibility to pay for the specified services/tests and pick a   payment method from among those accessible. To preserve user confidence, it   is critical to guarantee that the payment gateway is safe and dependable.
FR6 | Searching Labs | Labs.php | This requirement enables customers to   search for laboratories based on criteria such as location, availability,   services provided, ratings, and reviews. It is a significant feature since it   allows users to simply identify and select a lab depending on their needs.
FR7 | view the test results | Lab_test_detail.php | This functional need enables customers to   access their test results online once they have been administered. The test   results must be provided in a clear and simple way, and the user must be able   to check their previous test results.
FR8 | view the medical history | Lab_test.php | This functional requirement enables the   user to access their medical history, which includes past test results and   other pertinent medical information. This feature can help users maintain   track of their health progress and give doctors access to the patient's whole   medical history.
FR9 | View/ update profile | User.php | This functional requirement will enable   users to access and edit their personal profile information, contact   information, and other information. This feature will improve the customer   experience by offering personalized customized service. It will also assist   the system in keeping user information up to current and correct.
FR10 | Provide feedback about enquiries | contact.php | This functional requirement enables   customers to submit feedback on their inquiries, which can assist to enhance   customer service quality and resolve any issues or concerns that users may   have. It is critical to have a feedback mechanism in place so that the system   may be continually enhanced and appropriate to the demands of the users.
FR11 | Login/Logout | Signin.php | This is a necessary functional requirement   for user authentication and access control. It allows users to safely log in   to the system and log out when finished. It protects user data and prevents   illegal access.
Admin   Module
FR12 | Login into the System/ logout | Signin.php | From the standpoint of the admin module,   the "Login into the System/Logout" functional requirement relates   to an admin user's ability to log in and out of the system. This capability   is essential for ensuring that only authorized individuals have access to   sensitive system information and may conduct privileged activities.
FR13 | Search, add, update, edit, delete the   details of user | Users.php, user_detail.php | The functional requirement "Search,   add, update, edit, and delete the details of a user" relates to the   admin module's ability to handle user accounts. Administrators would be able   to search for particular user accounts, add new users, update the data of   current users, edit user accounts to remedy problems or make changes, and remove   user accounts as needed under this requirement.
FR14 | Generate the test report | Lab_test_detail.php | The ability to produce and see test reports   allows the administrator to generate and examine test reports for patients.   Using the patient's ID or other pertinent information, the administrator can   gain access to the test report.
FR15 | Tracking the transaction, generating the   invoice. | Payments.php, invoice.php | This implies that the system should be able   to track all transactions associated with the user's appointments and   generate invoices for them. This capability can aid in the maintenance of the   system's financial records and provide transparency in the billing process.   It would also offer the administrator with a clear picture of all   transactions and improved financial control of the system.
FR16 | Update/ edit report details | Lab_test.php, lab_test_detail.php | This enables admin to make modifications to   a test report's data, such as adding or amending test findings, updating   patient information, or correcting mistakes. This function is critical for   checking the report's correctness and completeness, as well as allowing the   administrator to make any required changes before finishing the report.
FR17 | Generating prescriptions | lab_test_detail.php | It refers to the admin module's capacity to   issue prescriptions for users/patients depending on test results. The admin   module should provide a user-friendly interface for producing prescriptions,   as well as the ability for the admin to enter essential information such as   the user's name, the type of test, and the test results. The produced   prescription should be accurate and easy for the user to comprehend, and it   should include any essential instructions for the user to follow.
FR18 | Billing and payment management | Payments.php | This requirement refers to the system's   capacity to manage the financial elements of lab services, such as invoicing   and payment processing. The admin should be able to produce and manage   invoices for each user, as well as manage payment methods and track   transactions.
FR19 | View User Feedback | Lab_test_detail.php | The functional requirement "View User   Feedback" is important since it allows patients to express their   thoughts and ideas about the system. By looking at this feedback, the system   can find areas for development as well as resolve any patient issues or   challenges. This feedback communication between patients and doctors   grows connection, developing trust and understanding of each other.   Doctors can get important knowledge from patient feedback, allowing them to   make well-informed decisions and improve the system to meet the requirements   of their patients.
FR20 | Updating tests prices | Services.detail | This requirement relates to the capacity to   change the costs of the system's various services or tests. This feature   allows the administrator to change the prices based on numerous criteria such   as market trends, operating expenses, and so on.
FR21 | Assigning ID to the user/patients |   | The admin module should be able to issue   unique IDs to each user/patient so that records, appointments, and test   results can be readily tracked. This will aid in the effective operation of   the system and prevent any record confusion or duplication. The issued IDs   should be unique, alphanumeric, and easy for users/patients to remember.
FR22 | Collecting Information’s. | Users.php, labtest.php, payment.php, appointments.php | It refers to the process of acquiring and   recording pertinent data on users, which can include as their medical   history, test results, payment, vital information. To maintain data privacy   and security, admin module should be capable of safely and correctly   collecting, storing, and managing user data.
FR23 | Authenticating patients. | Signup.php | From the perspective of the admin   module, it implies confirming the patient's identity and credentials to   guarantee that they are legitimate and permitted to access the medical   services provided by the system. This procedure may entail gathering personal   information from the patient, such as name, date of birth, contact   information, and medical history, and then confirming it against government   records or other reliable sources.
FR24 | System Authorization. | Signin.php | The process of controlling user access to   different system operations, features, and data is referred to as system   authorization. Based on their roles and responsibilities, administrators must   design and allocate different degrees of access and permissions to users. It   guarantees that only authorized users may execute certain actions or have   access to specific information within the system.



<p class=MsoNormal style='margin-bottom:0cm;line-height:200%'><b><span
lang=EN-US style='font-size:12.0pt;line-height:200%;font-family:"Times New Roman",serif;
color:black;mso-themecolor:text1'><o:p>&nbsp;</o:p></span></b></p>

<b><span lang=EN-US style='font-size:12.0pt;line-height:115%;font-family:"Times New Roman",serif;
mso-fareast-font-family:Calibri;mso-fareast-theme-font:minor-latin;color:black;
mso-themecolor:text1;mso-ansi-language:EN-US;mso-fareast-language:EN-US;
mso-bidi-language:AR-SA'>Non-Functional Requiremen</span></b>
</body>

</html>
